export enum RedisKeys {
   GET_ALL_USERS = 'GET_ALL_USERS',
   COUNT_GET_ALL_USERS = 'COUNT_GET_ALL_USERS',
   CURRENT_PAGE_GET_ALL_USERS = 'CURRENT_PAGE_GET_ALL_USERS',
   GET_SUGGESTED_USERS = 'GET_SUGGESTED_USERS',
   COUNT_GET_SUGGESTED_USERS = 'COUNT_GET_SUGGESTED_USERS',
   CURRENT_PAGE_GET_SUGGESTED_USERS = 'CURRENT_PAGE_GET_SUGGESTED_USERS',
   SEARCH_ALL_USERS = 'SEARCH_ALL_USERS',
   COUNT_SEARCH_ALL_USERS = 'COUNT_SEARCH_ALL_USERS',
   CURRENT_PAGE_SEARCH_ALL_USERS = 'CURRENT_PAGE_SEARCH_ALL_USERS',
}
